
const avatar1 = require('../../assets/profilepics/face1.jpg')
const avatar2 = require('../../assets/profilepics/face2.jpg')
const avatar3 = require('../../assets/profilepics/face3.jpg')

const art1 = require('../../assets/category/art1.jpg')
const art2 = require('../../assets/category/art2.jpg')
const art3 = require('../../assets/category/art3.jpg')
const art4 = require('../../assets/category/art4.jpg')

const build1 = require('../../assets/category/build1.jpeg')
const build2 = require('../../assets/category/build2.jpeg')
const build3 = require('../../assets/category/build3.jpeg')
const build4 = require('../../assets/category/build4.jpeg')

const wearables1 = require('../../assets/category/wearables1.jpg')
const wearables2 = require('../../assets/category/wearables2.jpg')
const wearables3 = require('../../assets/category/wearables3.jpg')
const wearables4 = require('../../assets/category/wearables4.jpg')

const land1 = require('../../assets/category/land1.jpg')
const land2 = require('../../assets/category/land2.jpg')
const land3 = require('../../assets/category/land3.jpg')
const land4 = require('../../assets/category/land4.jpg')

const pets1 = require('../../assets/category/pets1.jpg')
const pets2 = require('../../assets/category/pets2.jpg')
const pets3 = require('../../assets/category/pets3.jpg')
const pets4 = require('../../assets/category/pets4.jpg')

const miscellaneous1 = require('../../assets/category/miscellaneous1.jpg')
const miscellaneous2 = require('../../assets/category/miscellaneous2.jpg')
const miscellaneous3 = require('../../assets/category/miscellaneous3.jpg')
const miscellaneous4 = require('../../assets/category/miscellaneous4.jpg')

const time_icon = require('../../assets/auction/time_icon.png')

// const avatar1 = require('../../assets/profilepics/face7.jpg')
// const avatar2 = require('../../assets/profilepics/face8.jpg')
// const avatar3 = require('../../assets/profilepics/face9.jpg')
const avatar4 = require('../../assets/profilepics/face10.jpg')
const avatar5 = require('../../assets/profilepics/face11.jpg')
const avatar6 = require('../../assets/profilepics/face12.jpg')
const avatar7 = require('../../assets/profilepics/face13.jpg')
const avatar8 = require('../../assets/profilepics/face14.jpg')

const nft1 = require('../../assets/nfts/12.png')
const nft2 = require('../../assets/nfts/8.png')
const nft3 = require('../../assets/nfts/11.png')
const nft4 = require('../../assets/nfts/10.png')
const nft5 = require('../../assets/nfts/3.png')
const nft6 = require('../../assets/nfts/9.png')
const nft7 = require('../../assets/nfts/2.png')
const nft8 = require('../../assets/nfts/4.png')


export const CollectionsData = [
    {
        id:1,
        name:"MetaPets",
        c_name:"Realistic Art",
        sub_name:"sara Hayam",
        c_sub_name:"Chriss Avans",
        likes:350,
        c_likes:150,
        avatar:avatar1,
        grid_img1:art1,
        grid_img2:art2,
        grid_img3:art3,
        grid_img4:art4,
    },
    {
        id:2,
        name:"My Streets",
        c_name:"Sky high Buildings",
        sub_name:"Rossa wanda",
        c_sub_name:"Satty",
        likes:150,
        c_likes:150,
        avatar:avatar2,
        grid_img1:build1,
        grid_img2:build2,
        grid_img3:build3,
        grid_img4:build4,
    },
    {
        id:3,
        name:"Football is Life",
        c_name:"Smart Wearables",
        sub_name:"Rooney bloc",
        c_sub_name:"Sarah Coti",
        likes:882,
        c_likes:150,
        avatar:avatar3,
        grid_img1:wearables1,
        grid_img2:wearables2,
        grid_img3:wearables3,
        grid_img4:wearables4,
    },
    {
        id:4,
        name:"MetaPets",
        c_name:"Virtual Real Estate",
        sub_name:"sara Hayam",
        c_sub_name:"sara Hayam",
        likes:350,
        c_likes:150,
        avatar:avatar1,
        grid_img1:land1,
        grid_img2:land2,
        grid_img3:land3,
        grid_img4:land4,
    },
    {
        id:5,
        name:"My Streets",
        c_name:"Friendly Meta pets",
        sub_name:"Rossa wanda",
        c_sub_name:"Rossa wanda",
        likes:150,
        c_likes:150,
        avatar:avatar2,
        grid_img1:pets1,
        grid_img2:pets2,
        grid_img3:pets3,
        grid_img4:pets4,
    },
    {
        id:6,
        name:"Football is Life",
        c_name:"Miscellaneous",
        sub_name:"Rooney bloc",
        c_sub_name:"Rooney bloc",
        likes:882,
        c_likes:150,
        avatar:avatar3,
        grid_img1:miscellaneous1,
        grid_img2:miscellaneous2,
        grid_img3:miscellaneous3,
        grid_img4:miscellaneous4,
    },
]
export const CollectionsDataDynamic = [
    {
        id:1,
        name:"MetaPets",
        category:"art",
        c_name:"Realistic Art",
        sub_name:"sara Hayam",
        c_sub_name:"Chriss Avans",
        likes:350,
        c_likes:150,
        avatar:avatar1,
        grid_img1:art1,
        grid_img2:art2,
        grid_img3:art3,
        grid_img4:art4,
        nft:[
            {
              id:1,
              icon:avatar1,
              avatar:nft1,
              avatar_name:"JimXVlc",
              time:"02:15:10",
              name:"Passion Jacket",
              price:5.1,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sdasdasditting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!. on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!. on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adamada will john name",
              collection:"Food for thoughts Food for thoughts Food for thoughts" ,
              price_dollar:"($1.073)",
              outoff:"23 of 100",
            },
            {
              id:2,
              icon:avatar2,
              avatar:nft2,
              avatar_name:"BunnyBun",
              time:"05:28:15",
              name:"Leaf",
              price:4.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Meta Pets",
              price_dollar:"($1.073)",
              outoff:"23 of 100",
        
            },
            {
              id:3,
              icon:avatar3,
              avatar:nft3,
              avatar_name:"Samantha W",
              time:"02:16:27",
              name:"White Golden Retriver",
              price:2.9,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Football for life",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:4,
              icon:avatar4,
              avatar:nft4,
              avatar_name:"Jordan Nico",
              time:"02:16:27",
              name:"Mountains with a twist",
              price:7.6,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Spaces that inspire",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:5,
              icon:avatar5,
              avatar:nft5,
              avatar_name:"Sara Hayam",
              time:"02:15:10",
              name:"Paint Brush",
              price:3.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Black power cars",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:6,
              icon:avatar6,
              avatar:nft6,
              avatar_name:"Rossa Wanda",
              time:"05:28:15",
              name:"Diamond Stone",
              price:9.8,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Luxury in Pink",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:7,
              icon:avatar7,
              avatar:nft7,
              avatar_name:"Adam Newman",
              time:"02:16:27",
              name:"Music Box",
              price:1.0,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Look Out",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:8,
              icon:avatar8,
              avatar:nft8,
              avatar_name:"David Warner",
              time:"02:16:27",
              name:"Gifts",
              price:12.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Hello Sunshine",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
          ]
    },
    {
        id:2,
        name:"My Streets",
        category:"buildings",
        c_name:"Sky high Buildings",
        sub_name:"Rossa wanda",
        c_sub_name:"Satty",
        likes:150,
        c_likes:150,
        avatar:avatar2,
        grid_img1:build1,
        grid_img2:build2,
        grid_img3:build3,
        grid_img4:build4,
        nft:[
            {
              id:1,
              icon:avatar1,
              avatar:nft1,
              avatar_name:"JimXVlc",
              time:"02:15:10",
              name:"Passion Jacket",
              price:5.1,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sdasdasditting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!. on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!. on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adamada will john name",
              collection:"Food for thoughts Food for thoughts Food for thoughts" ,
              price_dollar:"($1.073)",
              outoff:"23 of 100",
              
            },
            {
              id:2,
              icon:avatar2,
              avatar:nft2,
              avatar_name:"BunnyBun",
              time:"05:28:15",
              name:"Leaf",
              price:4.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Meta Pets",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:3,
              icon:avatar3,
              avatar:nft3,
              avatar_name:"Samantha W",
              time:"02:16:27",
              name:"White Golden Retriver",
              price:2.9,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Football for life",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:4,
              icon:avatar4,
              avatar:nft4,
              avatar_name:"Jordan Nico",
              time:"02:16:27",
              name:"Mountains with a twist",
              price:7.6,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Spaces that inspire",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:5,
              icon:avatar5,
              avatar:nft5,
              avatar_name:"Sara Hayam",
              time:"02:15:10",
              name:"Paint Brush",
              price:3.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Black power cars",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:6,
              icon:avatar6,
              avatar:nft6,
              avatar_name:"Rossa Wanda",
              time:"05:28:15",
              name:"Diamond Stone",
              price:9.8,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Luxury in Pink",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:7,
              icon:avatar7,
              avatar:nft7,
              avatar_name:"Adam Newman",
              time:"02:16:27",
              name:"Music Box",
              price:1.0,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Look Out",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:8,
              icon:avatar8,
              avatar:nft8,
              avatar_name:"David Warner",
              time:"02:16:27",
              name:"Gifts",
              price:12.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Hello Sunshine",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
          ]
    },
    {
        id:3,
        name:"Football is Life",
        category:"wearables",
        c_name:"Smart Wearables",
        sub_name:"Rooney bloc",
        c_sub_name:"Sarah Coti",
        likes:882,
        c_likes:150,
        avatar:avatar3,
        grid_img1:wearables1,
        grid_img2:wearables2,
        grid_img3:wearables3,
        grid_img4:wearables4,
        nft:[
            {
              id:1,
              icon:avatar1,
              avatar:nft1,
              avatar_name:"JimXVlc",
              time:"02:15:10",
              name:"Passion Jacket",
              price:5.1,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sdasdasditting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!. on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!. on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adamada will john name",
              collection:"Food for thoughts Food for thoughts Food for thoughts" ,
              price_dollar:"($1.073)",
              outoff:"23 of 100",
            },
            {
              id:2,
              icon:avatar2,
              avatar:nft2,
              avatar_name:"BunnyBun",
              time:"05:28:15",
              name:"Leaf",
              price:4.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Meta Pets",
              price_dollar:"($1.073)",
              outoff:"23 of 100",
        
            },
            {
              id:3,
              icon:avatar3,
              avatar:nft3,
              avatar_name:"Samantha W",
              time:"02:16:27",
              name:"White Golden Retriver",
              price:2.9,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Football for life",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:4,
              icon:avatar4,
              avatar:nft4,
              avatar_name:"Jordan Nico",
              time:"02:16:27",
              name:"Mountains with a twist",
              price:7.6,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Spaces that inspire",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:5,
              icon:avatar5,
              avatar:nft5,
              avatar_name:"Sara Hayam",
              time:"02:15:10",
              name:"Paint Brush",
              price:3.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Black power cars",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:6,
              icon:avatar6,
              avatar:nft6,
              avatar_name:"Rossa Wanda",
              time:"05:28:15",
              name:"Diamond Stone",
              price:9.8,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Luxury in Pink",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:7,
              icon:avatar7,
              avatar:nft7,
              avatar_name:"Adam Newman",
              time:"02:16:27",
              name:"Music Box",
              price:1.0,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Look Out",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:8,
              icon:avatar8,
              avatar:nft8,
              avatar_name:"David Warner",
              time:"02:16:27",
              name:"Gifts",
              price:12.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Hello Sunshine",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
          ]
    },
    {
        id:4,
        name:"MetaPets",
        category:"virtualrealestate",
        c_name:"Virtual Real Estate",
        sub_name:"sara Hayam",
        c_sub_name:"sara Hayam",
        likes:350,
        c_likes:150,
        avatar:avatar1,
        grid_img1:land1,
        grid_img2:land2,
        grid_img3:land3,
        grid_img4:land4,
        nft:[
            {
              id:1,
              icon:avatar1,
              avatar:nft1,
              avatar_name:"JimXVlc",
              time:"02:15:10",
              name:"Passion Jacket",
              price:5.1,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sdasdasditting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!. on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!. on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adamada will john name",
              collection:"Food for thoughts Food for thoughts Food for thoughts" ,
              price_dollar:"($1.073)",
              outoff:"23 of 100",
            },
            {
              id:2,
              icon:avatar2,
              avatar:nft2,
              avatar_name:"BunnyBun",
              time:"05:28:15",
              name:"Leaf",
              price:4.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Meta Pets",
              price_dollar:"($1.073)",
              outoff:"23 of 100",
        
            },
            {
              id:3,
              icon:avatar3,
              avatar:nft3,
              avatar_name:"Samantha W",
              time:"02:16:27",
              name:"White Golden Retriver",
              price:2.9,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Football for life",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
           
          ]
    },
    {
        id:5,
        name:"My Streets",
        category:"metapets",
        c_name:"Friendly Meta pets",
        sub_name:"Rossa wanda",
        c_sub_name:"Rossa wanda",
        likes:150,
        c_likes:150,
        avatar:avatar2,
        grid_img1:pets1,
        grid_img2:pets2,
        grid_img3:pets3,
        grid_img4:pets4,
        nft:[
            {
              id:1,
              icon:avatar1,
              avatar:nft1,
              avatar_name:"JimXVlc",
              time:"02:15:10",
              name:"Passion Jacket",
              price:5.1,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sdasdasditting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!. on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!. on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adamada will john name",
              collection:"Food for thoughts Food for thoughts Food for thoughts" ,
              price_dollar:"($1.073)",
              outoff:"23 of 100",
            },
            {
              id:2,
              icon:avatar2,
              avatar:nft2,
              avatar_name:"BunnyBun",
              time:"05:28:15",
              name:"Leaf",
              price:4.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Meta Pets",
              price_dollar:"($1.073)",
              outoff:"23 of 100",
        
            },
            {
              id:3,
              icon:avatar3,
              avatar:nft3,
              avatar_name:"Samantha W",
              time:"02:16:27",
              name:"White Golden Retriver",
              price:2.9,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Football for life",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:4,
              icon:avatar4,
              avatar:nft4,
              avatar_name:"Jordan Nico",
              time:"02:16:27",
              name:"Mountains with a twist",
              price:7.6,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Spaces that inspire",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:5,
              icon:avatar5,
              avatar:nft5,
              avatar_name:"Sara Hayam",
              time:"02:15:10",
              name:"Paint Brush",
              price:3.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Black power cars",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:6,
              icon:avatar6,
              avatar:nft6,
              avatar_name:"Rossa Wanda",
              time:"05:28:15",
              name:"Diamond Stone",
              price:9.8,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Luxury in Pink",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            }
          ]
    },
    {
        id:6,
        name:"Football is Life",
        category:"miscellaneous",
        c_name:"Miscellaneous",
        sub_name:"Rooney bloc",
        c_sub_name:"Rooney bloc",
        likes:882,
        c_likes:150,
        avatar:avatar3,
        grid_img1:miscellaneous1,
        grid_img2:miscellaneous2,
        grid_img3:miscellaneous3,
        grid_img4:miscellaneous4,
        nft:[
            {
              id:1,
              icon:avatar1,
              avatar:nft1,
              avatar_name:"JimXVlc",
              time:"02:15:10",
              name:"Passion Jacket",
              price:5.1,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sdasdasditting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!. on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!. on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adamada will john name",
              collection:"Food for thoughts Food for thoughts Food for thoughts" ,
              price_dollar:"($1.073)",
              outoff:"23 of 100",
            },
            {
              id:2,
              icon:avatar2,
              avatar:nft2,
              avatar_name:"BunnyBun",
              time:"05:28:15",
              name:"Leaf",
              price:4.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Meta Pets",
              price_dollar:"($1.073)",
              outoff:"23 of 100",
        
            },
            {
              id:3,
              icon:avatar3,
              avatar:nft3,
              avatar_name:"Samantha W",
              time:"02:16:27",
              name:"White Golden Retriver",
              price:2.9,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Football for life",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:4,
              icon:avatar4,
              avatar:nft4,
              avatar_name:"Jordan Nico",
              time:"02:16:27",
              name:"Mountains with a twist",
              price:7.6,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Spaces that inspire",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:5,
              icon:avatar5,
              avatar:nft5,
              avatar_name:"Sara Hayam",
              time:"02:15:10",
              name:"Paint Brush",
              price:3.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Black power cars",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:6,
              icon:avatar6,
              avatar:nft6,
              avatar_name:"Rossa Wanda",
              time:"05:28:15",
              name:"Diamond Stone",
              price:9.8,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"Put On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Luxury in Pink",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:7,
              icon:avatar7,
              avatar:nft7,
              avatar_name:"Adam Newman",
              time:"02:16:27",
              name:"Music Box",
              price:1.0,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Look Out",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
            {
              id:8,
              icon:avatar8,
              avatar:nft8,
              avatar_name:"David Warner",
              time:"02:16:27",
              name:"Gifts",
              price:12.5,
              chain:"BLOQS",
              button_name:"Place Bid",
              nftdetails_button:"Make Offer",
              profile_button:"On Sale",
              time_icon:time_icon,
              view:780,
              like:250,
              description:"Sitting on your Shoulder is the most complicated object in the known universe. Collect 3D Rendered Brainy Arts. Trade now!.",
              createdby:"Garry Adam",
              collection:"Hello Sunshine",
              price_dollar:"($1.073)",
              outoff:"23 of 100"
        
            },
          ]
    },
]